export const HORTIFRUTI: { group: string; items: string[] }[] = [
  {
    group: "Folhas e verduras",
    items: [
      "Alface Americana",
      "Alface Crespa",
      "Alface Lisa",
      "Alface Roxa",
      "Rúcula",
      "Agrião",
      "Espinafre",
      "Couve-manteiga",
      "Couve-chinesa",
      "Repolho Verde",
      "Repolho Roxo",
      "Acelga",
      "Almeirão",
      "Chicória",
      "Salsa",
      "Cebolinha",
      "Coentro",
      "Manjericão",
      "Hortelã",
      "Alho-poró",
      "Alcachofra",
      "Catalonha",
      "Escarola",
      "Mostarda",
      "Salsão",
      "Taioba",
    ],
  },
  {
    group: "Legumes",
    items: [
      "Tomate Italiano",
      "Tomate Cereja",
      "Tomate Caqui",
      "Tomate Débora",
      "Pimentão Vermelho",
      "Pimentão Verde",
      "Pimentão Amarelo",
      "Abobrinha Italiana",
      "Abobrinha Brasileira",
      "Berinjela",
      "Pepino Comum",
      "Pepino Japonês",
      "Quiabo",
      "Jiló",
      "Chuchu",
      "Abóbora Cabotiá",
      "Abóbora Moranga",
      "Milho-verde",
      "Vagem",
      "Ervilha",
      "Maxixe",
      "Pimenta",
      "Tomate Grape",
      "Tomate Salada",
    ],
  },
  {
    group: "Raízes, tubérculos e bulbos",
    items: [
      "Cenoura",
      "Beterraba",
      "Batata Inglesa",
      "Batata-doce",
      "Mandioquinha-salsa",
      "Mandioca",
      "Inhame",
      "Cará",
      "Rabanete",
      "Nabo",
      "Gengibre",
      "Alho",
      "Cebola",
    ],
  },
  {
    group: "Brócolis, couves e repolhos",
    items: ["Brócolis Ninja", "Brócolis Ramoso", "Couve-flor", "Couve-de-bruxelas"],
  },
  {
    group: "Frutas",
    items: [
      "Banana Prata",
      "Banana Nanica",
      "Banana-da-terra",
      "Maçã Gala",
      "Maçã Fuji",
      "Pera",
      "Mamão Formosa",
      "Mamão Papaya",
      "Melancia",
      "Melão",
      "Abacaxi",
      "Manga Palmer",
      "Manga Tommy",
      "Laranja Pera",
      "Laranja Lima",
      "Tangerina",
      "Limão Tahiti",
      "Limão Siciliano",
      "Maracujá",
      "Goiaba",
      "Abacate",
      "Uva",
      "Morango",
      "Kiwi",
      "Coco-verde",
      "Laranja Pera Rio",
      "Laranja Pera Natal",
      "Tangerina Ponkan",
      "Tangerina Cravo",
      "Tangerina Murcott",
      "Pitaya Roxa",
      "Pitaya Amarela",
      "Pitaya Branca",
      "Figo",
      "Mamão",
      "Acerola",
      "Ameixa",
      "Amora",
      "Atemoia",
      "Caju",
      "Caqui",
      "Carambola",
      "Framboesa",
      "Fruta-do-conde",
      "Jabuticaba",
      "Jaca",
      "Lichia",
      "Mirtilo",
      "Nectarina",
      "Nêspera",
      "Pêssego",
    ],
  },
  {
    group: "Ervas e Temperos",
    items: [
      "Alecrim",
      "Tomilho",
      "Sálvia",
      "Orégano",
      "Louro",
      "Cebolete",
      "Capim-cidreira",
      "Endro",
      "Erva-doce",
      "Manjerona",
    ],
  },
  {
    group: "Leite e Derivados",
    items: [
      "Leite Pasteurizado Integral",
      "Leite Pasteurizado Semidesnatado",
      "Leite Pasteurizado Desnatado",
      "Leite de Cabra",
      "Leite de Ovelha",
      "Muçarela",
      "Queijo Minas Frescal",
      "Queijo Coalho",
      "Queijo Prato",
      "Queijo Parmesão",
      "Requeijão Cremoso",
      "Manteiga",
      "Iogurte Natural",
      "Iogurte de Frutas",
      "Doce de Leite",
      "Leite Condensado",
      "Creme de Leite",
      "Ricota",
      "Queijo Coalho para Churrasco",
    ],
  },
];

export const ALL_HORTIFRUTI = HORTIFRUTI.flatMap((g) => g.items);

export const NEW_SUPPLIER_PRODUCTS: { group: string; items: string[] }[] = [
  {
    group: "Mel e derivados",
    items: [
      "Mel",
      "Mel Silvestre",
      "Mel de Laranjeira",
      "Mel de Eucalipto",
      "Mel de Assa-peixe",
      "Mel em Favo",
      "Extrato de Própolis",
      "Própolis in Natura",
      "Pólen Apícola",
      "Geleia Real",
      "Cera de Abelha",
    ],
  },
  {
    group: "Doces, geleias e conservas artesanais",
    items: [
      "Doce de Figo Ramy",
      "Geleia de Laranja com Pimenta",
      "Geleia de Abacaxi com Pimenta",
      "Geleia de Amora com Morango",
      "Geleia de Manga com Maracujá",
      "Picles de Botão Floral de Pitaya",
      "Paçoca artesanal",
      "Cocada artesanal",
      "Doce de abóbora",
    ],
  },
  {
    group: "Massas, pães e bolos artesanais",
    items: [
      "Fettuccine de Pitaya",
      "Pão caseiro",
      "Bolacha de nata",
      "Bolo de milho",
      "Bolo de mandioca",
      "Bolo recheado de brigadeiro",
      "Bolo recheado de abacaxi",
    ],
  },
  {
    group: "Snacks artesanais",
    items: ["Chips de mandioca", "Chips de batata"],
  },
  {
    group: "Cafés",
    items: [
      "Café tradicional",
      "Café especial",
      "Café torrado em grãos",
      "Café torrado e moído",
      "Café orgânico",
      "Café gourmet",
    ],
  },
];

function uniqueSorted(items: string[]) {
  return Array.from(new Set(items)).sort((a, b) => a.localeCompare(b));
}

export const SUPPLIER_PRODUCT_GROUPS = [...HORTIFRUTI, ...NEW_SUPPLIER_PRODUCTS].map((group) => ({
  ...group,
  items: uniqueSorted(group.items),
}));

export const ALL_SUPPLIER_PRODUCTS = uniqueSorted(
  SUPPLIER_PRODUCT_GROUPS.flatMap((group) => group.items),
);
