export const HORTIFRUTI: { group: string; items: string[] }[] = [
  {
    group: "Hortaliças e Folhosos",
    items: [
      "Alface Americana",
      "Alface Crespa",
      "Alface Lisa",
      "Alface Roxa",
      "Rúcula",
      "Agrião",
      "Espinafre",
      "Couve Manteiga",
      "Couve Chinesa",
      "Repolho Verde",
      "Repolho Roxo",
      "Acelga",
      "Almeirão",
      "Chicória",
      "Salsa",
      "Cebolinha",
      "Coentro",
      "Manjericão",
      "Hortelã",
    ],
  },
  {
    group: "Legumes e Frutos",
    items: [
      "Tomate Italiano",
      "Tomate Cereja",
      "Tomate Caqui",
      "Tomate Débora",
      "Pimentão Vermelho",
      "Pimentão Verde",
      "Pimentão Amarelo",
      "Abobrinha Italiana",
      "Abobrinha Brasileira",
      "Berinjela",
      "Pepino Comum",
      "Pepino Japonês",
      "Quiabo",
      "Jiló",
      "Chuchu",
      "Abóbora Cabotiá",
      "Abóbora Moranga",
      "Milho Verde",
      "Vagem",
      "Ervilha",
    ],
  },
  {
    group: "Raízes e Tubérculos",
    items: [
      "Cenoura",
      "Beterraba",
      "Batata Inglesa",
      "Batata Doce",
      "Batata Baroa",
      "Mandioca",
      "Inhame",
      "Cará",
      "Rabanete",
      "Nabo",
      "Gengibre",
      "Alho",
      "Cebola",
    ],
  },
  {
    group: "Brássicas",
    items: ["Brócolis Ninja", "Brócolis Ramoso", "Couve-flor", "Couve de Bruxelas"],
  },
  {
    group: "Frutas",
    items: [
      "Banana Prata",
      "Banana Nanica",
      "Banana da Terra",
      "Maçã Gala",
      "Maçã Fuji",
      "Pera",
      "Mamão Formosa",
      "Mamão Papaya",
      "Melancia",
      "Melão",
      "Abacaxi",
      "Manga Palmer",
      "Manga Tommy",
      "Laranja Pera",
      "Laranja Lima",
      "Tangerina",
      "Limão Tahiti",
      "Limão Siciliano",
      "Maracujá",
      "Goiaba",
      "Abacate",
      "Uva",
      "Morango",
      "Kiwi",
      "Coco Verde",
      "Laranja Pera Rio",
      "Laranja Pera Natal",
      "Limão Taiti",
      "Poncã",
      "Tangerina Cravo",
      "Murcot",
      "Pitaya Roxa",
      "Pitaya Amarela",
      "Pitaya Branca",
      "Figo",
      "Mamão",
      "Amora e Morango",
      "Manga e Maracujá",
    ],
  },
  {
    group: "Ervas e Temperos",
    items: ["Alecrim", "Tomilho", "Sálvia", "Orégano", "Louro", "Cebolete"],
  },
  {
    group: "Leite e Derivados",
    items: [
      "Leite Pasteurizado Integral",
      "Leite Pasteurizado Semi-desnatado",
      "Leite Pasteurizado Desnatado",
      "Leite Cru",
      "Leite de Cabra",
      "Leite de Ovelha",
      "Mussarela",
      "Queijo Minas Frescal",
      "Queijo Coalho",
      "Queijo Prato",
      "Queijo Parmesão",
      "Requeijão Cremoso",
      "Manteiga",
      "Iogurte Natural",
      "Iogurte de Frutas",
      "Doce de Leite",
      "Leite Condensado",
      "Creme de Leite",
      "Ricota",
      "Coalho para Churrasco",
    ],
  },
];

export const ALL_HORTIFRUTI = HORTIFRUTI.flatMap((g) => g.items);

export const NEW_SUPPLIER_PRODUCTS: { group: string; items: string[] }[] = [
  {
    group: "Doces, geleias e conservas artesanais",
    items: [
      "Doce Figo Ramy",
      "Geleia laranja com pimenta",
      "Abacaxi com pimenta",
      "Picles de Botão Floral de Pitaya",
      "Paçoca artesanal",
      "Cocada artesanal",
      "Doce de abóbora",
    ],
  },
  {
    group: "Massas, pães e bolos artesanais",
    items: [
      "Fettuccine de Pitaya",
      "Pão caseiro",
      "Bolacha de nata",
      "Bolo de milho",
      "Bolo de mandioca",
      "Bolo recheado de brigadeiro",
      "Bolo recheado de abacaxi",
    ],
  },
  {
    group: "Snacks artesanais",
    items: ["Chips de mandioca", "Chips de batata"],
  },
  {
    group: "Cafés",
    items: [
      "Café tradicional",
      "Café especial",
      "Café torrado em grãos",
      "Café torrado e moído",
      "Café orgânico",
      "Café gourmet",
    ],
  },
];

function uniqueSorted(items: string[]) {
  return Array.from(new Set(items)).sort((a, b) => a.localeCompare(b));
}

export const SUPPLIER_PRODUCT_GROUPS = [...HORTIFRUTI, ...NEW_SUPPLIER_PRODUCTS].map((group) => ({
  ...group,
  items: uniqueSorted(group.items),
}));

export const ALL_SUPPLIER_PRODUCTS = uniqueSorted(
  SUPPLIER_PRODUCT_GROUPS.flatMap((group) => group.items),
);
