/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as RatingRouteImport } from './routes/rating'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemandsRouteImport } from './routes/demands'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupProducerRouteImport } from './routes/signup.producer'
import { Route as SignupOrganizationRouteImport } from './routes/signup.organization'
import { Route as SignupBuyerRouteImport } from './routes/signup.buyer'
import { Route as SignupAdminRouteImport } from './routes/signup.admin'
import { Route as ProfileProducerRouteImport } from './routes/profile.producer'
import { Route as ProfileOrganizationRouteImport } from './routes/profile.organization'
import { Route as ProfileBuyerRouteImport } from './routes/profile.buyer'
import { Route as ProducerOrdersRouteImport } from './routes/producer.orders'
import { Route as OrganizationsNegotiationsRouteImport } from './routes/organizations.negotiations'
import { Route as OrganizationsMessagesRouteImport } from './routes/organizations.messages'
import { Route as OrganizationsMembersRouteImport } from './routes/organizations.members'
import { Route as DirectoryOrganizationsRouteImport } from './routes/directory.organizations'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingRoute = RatingRouteImport.update({
  id: '/rating',
  path: '/rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandsRoute = DemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupProducerRoute = SignupProducerRouteImport.update({
  id: '/signup/producer',
  path: '/signup/producer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupOrganizationRoute = SignupOrganizationRouteImport.update({
  id: '/signup/organization',
  path: '/signup/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupBuyerRoute = SignupBuyerRouteImport.update({
  id: '/signup/buyer',
  path: '/signup/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupAdminRoute = SignupAdminRouteImport.update({
  id: '/signup/admin',
  path: '/signup/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProducerRoute = ProfileProducerRouteImport.update({
  id: '/profile/producer',
  path: '/profile/producer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOrganizationRoute = ProfileOrganizationRouteImport.update({
  id: '/profile/organization',
  path: '/profile/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBuyerRoute = ProfileBuyerRouteImport.update({
  id: '/profile/buyer',
  path: '/profile/buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerOrdersRoute = ProducerOrdersRouteImport.update({
  id: '/producer/orders',
  path: '/producer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNegotiationsRoute =
  OrganizationsNegotiationsRouteImport.update({
    id: '/negotiations',
    path: '/negotiations',
    getParentRoute: () => OrganizationsRoute,
  } as any)
const OrganizationsMessagesRoute = OrganizationsMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OrganizationsRoute,
} as any)
const OrganizationsMembersRoute = OrganizationsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => OrganizationsRoute,
} as any)
const DirectoryOrganizationsRoute = DirectoryOrganizationsRouteImport.update({
  id: '/directory/organizations',
  path: '/directory/organizations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/demands': typeof DemandsRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/production': typeof ProductionRoute
  '/rating': typeof RatingRoute
  '/reset': typeof ResetRoute
  '/tracking': typeof TrackingRoute
  '/update-password': typeof UpdatePasswordRoute
  '/directory/organizations': typeof DirectoryOrganizationsRoute
  '/organizations/members': typeof OrganizationsMembersRoute
  '/organizations/messages': typeof OrganizationsMessagesRoute
  '/organizations/negotiations': typeof OrganizationsNegotiationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/profile/buyer': typeof ProfileBuyerRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/producer': typeof ProfileProducerRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/producer': typeof SignupProducerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/demands': typeof DemandsRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/production': typeof ProductionRoute
  '/rating': typeof RatingRoute
  '/reset': typeof ResetRoute
  '/tracking': typeof TrackingRoute
  '/update-password': typeof UpdatePasswordRoute
  '/directory/organizations': typeof DirectoryOrganizationsRoute
  '/organizations/members': typeof OrganizationsMembersRoute
  '/organizations/messages': typeof OrganizationsMessagesRoute
  '/organizations/negotiations': typeof OrganizationsNegotiationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/profile/buyer': typeof ProfileBuyerRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/producer': typeof ProfileProducerRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/producer': typeof SignupProducerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/chats': typeof ChatsRoute
  '/demands': typeof DemandsRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/production': typeof ProductionRoute
  '/rating': typeof RatingRoute
  '/reset': typeof ResetRoute
  '/tracking': typeof TrackingRoute
  '/update-password': typeof UpdatePasswordRoute
  '/directory/organizations': typeof DirectoryOrganizationsRoute
  '/organizations/members': typeof OrganizationsMembersRoute
  '/organizations/messages': typeof OrganizationsMessagesRoute
  '/organizations/negotiations': typeof OrganizationsNegotiationsRoute
  '/producer/orders': typeof ProducerOrdersRoute
  '/profile/buyer': typeof ProfileBuyerRoute
  '/profile/organization': typeof ProfileOrganizationRoute
  '/profile/producer': typeof ProfileProducerRoute
  '/signup/admin': typeof SignupAdminRoute
  '/signup/buyer': typeof SignupBuyerRoute
  '/signup/organization': typeof SignupOrganizationRoute
  '/signup/producer': typeof SignupProducerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/chats'
    | '/demands'
    | '/login'
    | '/order'
    | '/orders'
    | '/organizations'
    | '/portfolio'
    | '/production'
    | '/rating'
    | '/reset'
    | '/tracking'
    | '/update-password'
    | '/directory/organizations'
    | '/organizations/members'
    | '/organizations/messages'
    | '/organizations/negotiations'
    | '/producer/orders'
    | '/profile/buyer'
    | '/profile/organization'
    | '/profile/producer'
    | '/signup/admin'
    | '/signup/buyer'
    | '/signup/organization'
    | '/signup/producer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/chats'
    | '/demands'
    | '/login'
    | '/order'
    | '/orders'
    | '/organizations'
    | '/portfolio'
    | '/production'
    | '/rating'
    | '/reset'
    | '/tracking'
    | '/update-password'
    | '/directory/organizations'
    | '/organizations/members'
    | '/organizations/messages'
    | '/organizations/negotiations'
    | '/producer/orders'
    | '/profile/buyer'
    | '/profile/organization'
    | '/profile/producer'
    | '/signup/admin'
    | '/signup/buyer'
    | '/signup/organization'
    | '/signup/producer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/chats'
    | '/demands'
    | '/login'
    | '/order'
    | '/orders'
    | '/organizations'
    | '/portfolio'
    | '/production'
    | '/rating'
    | '/reset'
    | '/tracking'
    | '/update-password'
    | '/directory/organizations'
    | '/organizations/members'
    | '/organizations/messages'
    | '/organizations/negotiations'
    | '/producer/orders'
    | '/profile/buyer'
    | '/profile/organization'
    | '/profile/producer'
    | '/signup/admin'
    | '/signup/buyer'
    | '/signup/organization'
    | '/signup/producer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  ChatsRoute: typeof ChatsRoute
  DemandsRoute: typeof DemandsRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  ProductionRoute: typeof ProductionRoute
  RatingRoute: typeof RatingRoute
  ResetRoute: typeof ResetRoute
  TrackingRoute: typeof TrackingRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  DirectoryOrganizationsRoute: typeof DirectoryOrganizationsRoute
  ProducerOrdersRoute: typeof ProducerOrdersRoute
  ProfileBuyerRoute: typeof ProfileBuyerRoute
  ProfileOrganizationRoute: typeof ProfileOrganizationRoute
  ProfileProducerRoute: typeof ProfileProducerRoute
  SignupAdminRoute: typeof SignupAdminRoute
  SignupBuyerRoute: typeof SignupBuyerRoute
  SignupOrganizationRoute: typeof SignupOrganizationRoute
  SignupProducerRoute: typeof SignupProducerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating': {
      id: '/rating'
      path: '/rating'
      fullPath: '/rating'
      preLoaderRoute: typeof RatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demands': {
      id: '/demands'
      path: '/demands'
      fullPath: '/demands'
      preLoaderRoute: typeof DemandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/producer': {
      id: '/signup/producer'
      path: '/signup/producer'
      fullPath: '/signup/producer'
      preLoaderRoute: typeof SignupProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/organization': {
      id: '/signup/organization'
      path: '/signup/organization'
      fullPath: '/signup/organization'
      preLoaderRoute: typeof SignupOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/buyer': {
      id: '/signup/buyer'
      path: '/signup/buyer'
      fullPath: '/signup/buyer'
      preLoaderRoute: typeof SignupBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/admin': {
      id: '/signup/admin'
      path: '/signup/admin'
      fullPath: '/signup/admin'
      preLoaderRoute: typeof SignupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/producer': {
      id: '/profile/producer'
      path: '/profile/producer'
      fullPath: '/profile/producer'
      preLoaderRoute: typeof ProfileProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/organization': {
      id: '/profile/organization'
      path: '/profile/organization'
      fullPath: '/profile/organization'
      preLoaderRoute: typeof ProfileOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/buyer': {
      id: '/profile/buyer'
      path: '/profile/buyer'
      fullPath: '/profile/buyer'
      preLoaderRoute: typeof ProfileBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/orders': {
      id: '/producer/orders'
      path: '/producer/orders'
      fullPath: '/producer/orders'
      preLoaderRoute: typeof ProducerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/negotiations': {
      id: '/organizations/negotiations'
      path: '/negotiations'
      fullPath: '/organizations/negotiations'
      preLoaderRoute: typeof OrganizationsNegotiationsRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/messages': {
      id: '/organizations/messages'
      path: '/messages'
      fullPath: '/organizations/messages'
      preLoaderRoute: typeof OrganizationsMessagesRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/organizations/members': {
      id: '/organizations/members'
      path: '/members'
      fullPath: '/organizations/members'
      preLoaderRoute: typeof OrganizationsMembersRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/directory/organizations': {
      id: '/directory/organizations'
      path: '/directory/organizations'
      fullPath: '/directory/organizations'
      preLoaderRoute: typeof DirectoryOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrganizationsRouteChildren {
  OrganizationsMembersRoute: typeof OrganizationsMembersRoute
  OrganizationsMessagesRoute: typeof OrganizationsMessagesRoute
  OrganizationsNegotiationsRoute: typeof OrganizationsNegotiationsRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsMembersRoute: OrganizationsMembersRoute,
  OrganizationsMessagesRoute: OrganizationsMessagesRoute,
  OrganizationsNegotiationsRoute: OrganizationsNegotiationsRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  ChatsRoute: ChatsRoute,
  DemandsRoute: DemandsRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  ProductionRoute: ProductionRoute,
  RatingRoute: RatingRoute,
  ResetRoute: ResetRoute,
  TrackingRoute: TrackingRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  DirectoryOrganizationsRoute: DirectoryOrganizationsRoute,
  ProducerOrdersRoute: ProducerOrdersRoute,
  ProfileBuyerRoute: ProfileBuyerRoute,
  ProfileOrganizationRoute: ProfileOrganizationRoute,
  ProfileProducerRoute: ProfileProducerRoute,
  SignupAdminRoute: SignupAdminRoute,
  SignupBuyerRoute: SignupBuyerRoute,
  SignupOrganizationRoute: SignupOrganizationRoute,
  SignupProducerRoute: SignupProducerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
